ipAddress=127.0.0.1
port=4723

platformName=iOS
platformVersion=16.4
deviceName=iPhone 14 Pro
automationName=XCUITest
bundleId=com.confidential.confidential

number=confidential
password=confidential

preInvestDeepLinkUrl=confidential
postInvestDeepLinkUrl=confidential